;;       (list-matching-lines-face . bold)
;;       (view-highlight-face . highlight))

;;      (fringe ((t (:background "black"))))
;;      (font-lock-builtin-face ((t (:foreground "#aaccff"))))
;;      (font-lock-comment-face ((t (:italic t :foreground "#bb55ee"))))
;;      (font-lock-comment-delimiter-face ((t (:foreground "#9933cc"))))
;;      (font-lock-constant-face ((t (:foreground "#339999"))))
;;      (font-lock-function-name-face ((t (:foreground "#ffcc00"))))
;;      (font-lock-keyword-face ((t (:foreground "#ff6600"))))
;;      (font-lock-preprocessor-face ((t (:foreground "#aaffff"))))
;;      (font-lock-reference-face ((t (:foreground "LightSteelBlue"))))
;;      (font-lock-string-face ((t (:foreground "DarkOliveGreen3"))))
;;      (font-lock-doc-face ((t (:foreground "LightSalmon"))))
;;      (font-lock-type-face ((t (:italic t :foreground "burlywood3"))))
;;      (font-lock-variable-name-face ((t (:foreground "#aaccff"))))
;;      (font-lock-warning-face ((t (:bold t :foreground "Pink"))))
;;      (paren-face-match-light ((t (:background "#222222"))))
;;      (highlight ((t (:background "gray4"))))
;;      (modeline ((t (:background "#a5baf1" :foreground "black"))))
;;      (modeline-buffer-id ((t (:background "#a5baf1" :foreground
;; "black"))))
;;      (modeline-mousable ((t (:background "#a5baf1" :foreground
;; "black"))))
;;      (modeline-mousable-minor-mode ((t (:background
;; "#a5baf1" :foreground "black"))))
;;      (primary-selection ((t (:background "#555577"))))
;;      (secondary-selection ((t (:background "darkslateblue"))))
;;      (minibuffer-prompt ((t (:bold t :foreground "#ff6600")))))))


;; (scroll-bar-background . "grey75") (menu-bar-lines . 1) (right-fringe . 8) (left-fringe . 8) (border-color . "black")

;; (custom-set-faces
;;  '(autoface-default ((t (:inherit default :background "black" :foreground "White" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 141 :width normal :family "apple-monaco"))))
;;  '(font-lock-doc-face ((t (:foreground "white" :weight bold))))
;;  '(font-lock-function-name-face ((((type tty) (class color)) (:foreground "white" :weight bold))))
;;  '(font-lock-string-face ((((type tty) (class color)) (:foreground "green" :weight bold))))
;;  '(font-lock-type-face ((((type tty) (class color)) (:inherit font-lock-function-name-face :foreground "blue" :weight bold))))
;;  '(nxml-attribute-colon-face ((t (:inherit nxml-attribute-local-name-face))))
;;  '(nxml-attribute-local-name-face ((t (:foreground "DarkSeaGreen"))))
;;  '(nxml-attribute-prefix-face ((t (:inherit nxml-attribute-local-name-face))))
;;  '(nxml-attribute-value-delimiter-face ((t (:inherit nxml-tag-delimiter-face))))
;;  '(nxml-attribute-value-face ((t (:foreground "LightSteelBlue"))))
;;  '(nxml-comment-content-face ((t (:foreground "Sienna1"))))
;;  '(nxml-comment-delimiter-face ((t (:inherit nxml-comment-content-face))))
;;  '(nxml-delimited-data-face ((((class color) (background light)) (:inherit nxml-name-face))))
;;  '(nxml-delimiter-face ((t (:inherit nxml-name-face))))
;;  '(nxml-element-colon-face ((t (:inherit nxml-element-local-name-face))))
;;  '(nxml-element-local-name-face ((t (:foreground "Darkseagreen"))))
;;  '(nxml-element-prefix-face ((t (:inherit nxml-element-local-name-face))))
;;  '(nxml-entity-ref-name-face ((t (:inherit nxml-ref-face))))
;;  '(nxml-markup-declaration-delimiter-face ((t (:inherit nxml-prolog-literal-delimiter-face))))
;;  '(nxml-name-face ((t (:inherit nxml-element-local-name-face))))
;;  '(nxml-namespace-attribute-colon-face ((t (:inherit nxml-attribute-colon-face))))
;;  '(nxml-namespace-attribute-prefix-face ((t (:inherit nxml-attribute-local-name-face))))
;;  '(nxml-namespace-attribute-xmlns-face ((t (:inherit nxml-attribute-local-name-face))))
;;  '(nxml-processing-instruction-delimiter-face ((t (:inherit nxml-tag-delimiter-face))))
;;  '(nxml-prolog-keyword-face ((t (:inherit nxml-prolog-literal-delimiter-face))))
;;  '(nxml-prolog-literal-content-face ((t (:inherit nxml-prolog-literal-delimiter-face))))
;;  '(nxml-prolog-literal-delimiter-face ((t (:foreground "white"))))
;;  '(nxml-ref-face ((t (:foreground "white"))))
;;  '(nxml-tag-delimiter-face ((t (:foreground "SlateGrey"))))
;;  '(nxml-tag-slash-face ((t (:inherit nxml-tag-delimiter-face))))
;;  '(nxml-text-face ((t (:foreground "#cccccc")))))

(defun color-theme-aaken ()
  ((display-time-mail-face . mode-line)
   (help-highlight-face . underline)
   (list-matching-lines-face . bold)
										; ori:
										;      (rst-block-face . font-lock-keyword-face)
   (rst-block-face . font-lock-comment-face)
   (rst-comment-face . font-lock-comment-face)
   (rst-definition-face . font-lock-function-name-face)
   (rst-directive-face . font-lock-builtin-face)
   (rst-emphasis1-face quote italic)
   (rst-emphasis2-face quote bold)
   (rst-external-face . font-lock-type-face)
   (rst-literal-face . font-lock-string-face)
   (rst-reference-face . font-lock-variable-name-face)
   (widget-mouse-face . highlight))
  (default ((t (:stipple nil :background "black" :foreground "White" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 116 :width normal :family "apple-monaco"))))
     (Doc ((t (:foreground "Red"))))
     (Stop ((t (:background "Red" :foreground "White"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:bold t :weight bold))))
     (border ((t (:background "black"))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (:background "black" :foreground "white"))))
     (calendar-today-face ((t (:underline t))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (cperl-array-face ((t (:foreground "darkseagreen"))))
     (cperl-hash-face ((t (:foreground "darkseagreen"))))
     (cperl-nonoverridable-face ((t (:foreground "SkyBlue"))))
     (cursor ((t (:background "yellow"))))
     (custom-button-face ((t (nil))))
     (custom-changed-face ((t (:background "blue" :foreground "white"))))
     (custom-documentation-face ((t (nil))))
     (custom-face-tag-face ((t (:underline t))))
     (custom-group-tag-face ((t (:foreground "light blue" :underline t))))
     (custom-group-tag-face-1 ((t (:foreground "pink" :underline t))))
     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
     (custom-saved-face ((t (:underline t))))
     (custom-set-face ((t (:background "white" :foreground "blue"))))
     (custom-state-face ((t (:foreground "lime green"))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag-face ((t (:foreground "light blue" :underline t))))
     (diary-face ((t (:foreground "IndianRed"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "Grey"))))
     (eshell-ls-clutter-face ((t (:foreground "DimGray"))))
     (eshell-ls-directory-face ((t (:bold t :foreground "MediumSlateBlue" :weight bold))))
     (eshell-ls-executable-face ((t (:foreground "Coral"))))
     (eshell-ls-missing-face ((t (:foreground "black"))))
     (eshell-ls-picture-face ((t (:foreground "Violet"))))
     (eshell-ls-product-face ((t (:foreground "sandybrown"))))
     (eshell-ls-readonly-face ((t (:foreground "Aquamarine"))))
     (eshell-ls-special-face ((t (:foreground "Gold"))))
     (eshell-ls-symlink-face ((t (:foreground "White"))))
     (eshell-ls-unreadable-face ((t (:foreground "DimGray"))))
     (eshell-prompt-face ((t (:foreground "MediumAquamarine"))))
     (fixed-pitch ((t (:family "apple-monaco"))))
     (fl-comment-face ((t (:foreground "pink"))))
     (fl-doc-string-face ((t (:foreground "purple"))))
     (fl-function-name-face ((t (:foreground "red"))))
     (fl-keyword-face ((t (:foreground "cadetblue"))))
     (fl-string-face ((t (:foreground "green"))))
     (fl-type-face ((t (:foreground "yellow"))))
;     (font-lock-comment-face ((t (:foreground "SlateGrey"))))
; ori:

;     (font-lock-comment-face ((t (:foreground "Sienna2"))))
;     (font-lock-doc-face ((t (:bold t :foreground "white" :weight bold))))
; ori:
;     (font-lock-doc-string-face ((t (:foreground "pale green"))))
; ori:
;     (font-lock-string-face ((t (:foreground "pale green"))))

     (fringe ((t (:background "grey10"))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
     (header-line ((t (:box (:line-width 1 :style released-button) :background "grey20" :foreground "grey90" :box nil))))
     (highlight ((t (:background "darkolivegreen"))))
     (highline-face ((t (:background "SeaGreen"))))
     (holiday-face ((t (:background "DimGray"))))
     (info-menu-5 ((t (:underline t))))
     (info-node ((t (:bold t :foreground "DodgerBlue1" :underline t :weight bold))))
     (info-xref ((t (:foreground "DodgerBlue1" :underline t))))
     (italic ((t (nil))))
     (left-margin ((t (nil))))
     (list-mode-item-selected ((t (:background "gray68" :foreground "white"))))
     (menu ((t (nil))))
     (message-cited-text-face ((t (:bold t :foreground "green" :weight bold))))
     (message-header-cc-face ((t (:bold t :foreground "green4" :weight bold))))
     (message-header-name-face ((t (:bold t :foreground "orange" :weight bold))))
     (message-header-newsgroups-face ((t (:bold t :foreground "violet" :weight bold))))
     (message-header-other-face ((t (:bold t :foreground "chocolate" :weight bold))))
     (message-header-subject-face ((t (:bold t :foreground "yellow" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "cadetblue" :weight bold))))
     (message-header-xheader-face ((t (:bold t :foreground "light blue" :weight bold))))
     (message-mml-face ((t (:bold t :foreground "Green3" :weight bold))))
     (message-separator-face ((t (:foreground "blue3"))))
     (mode-line ((t (:background "DarkRed" :foreground "white" :box (:line-width 1 :style released-button)))))
     (modeline-buffer-id ((t (:background "DarkRed" :foreground "white"))))
     (modeline-mousable ((t (:background "DarkRed" :foreground "white"))))
     (modeline-mousable-minor-mode ((t (:background "DarkRed" :foreground "white"))))
     (mouse ((t (:background "sienna1"))))
     (p4-depot-added-face ((t (:foreground "blue"))))
     (p4-depot-deleted-face ((t (:foreground "red"))))
     (p4-depot-unmapped-face ((t (:foreground "grey30"))))
     (p4-diff-change-face ((t (:foreground "dark green"))))
     (p4-diff-del-face ((t (:foreground "red"))))
     (p4-diff-file-face ((t (:background "gray90"))))
     (p4-diff-head-face ((t (:background "gray95"))))
     (p4-diff-ins-face ((t (:foreground "blue"))))
     (pointer ((t (nil))))
     (primary-selection ((t (:background "blue"))))
     (qt-classes-face ((t (:foreground "Red"))))
     (red ((t (:foreground "red"))))
     (right-margin ((t (nil))))
     (scroll-bar ((t (:background "grey75"))))
     (secondary-selection ((t (:background "darkslateblue"))))
     (show-paren-match-face ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (show-paren-mismatch-face ((t (:background "Red" :foreground "White"))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (tool-bar ((t (nil))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red"))))
     (variable-pitch ((t (:family "apple-monaco"))))
     (vertical-divider ((t (nil))))
     (widget ((t (nil))))
     (widget-button-face ((t (:bold t :weight bold))))
     (widget-button-pressed-face ((t (:foreground "red"))))
     (widget-documentation-face ((t (:foreground "lime green"))))
     (widget-field-face ((t (:background "dim gray"))))
     (widget-inactive-face ((t (:foreground "light gray"))))
     (widget-single-line-field-face ((t (:background "dim gray"))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (:foreground "beige"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (yellow ((t (:foreground "yellow"))))
)

; ------------------------------------------------------------------------------

(defun color-theme-aaken-dark ()
  "Aaken Dark color theme by tav, created 2004-11-19"
  (interactive)
  (color-theme-install
   '(color-theme-aaken-dark
     ((background-color . "black")
	  (background-mode . dark)
	  (border-color . "black")
      (cursor-color . "yellow")
      (foreground-color . "white"))
     (default ((t (nil))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:italic t :bold t))))
     (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-comment-face ((t (:foreground "#e16955"))))
     (font-lock-constant-face ((t (:foreground "#54fff7"))))
     (font-lock-doc-face ((t (:foreground "grey"))))
     (font-lock-doc-string-face ((t (:foreground "#ff7a0a"))))
     (font-lock-function-name-face ((t (:foreground "#91e619"))))
     (font-lock-keyword-face ((t (:foreground "#54fff7"))))
     (font-lock-preprocessor-face ((t (:foreground "#54fff7"))))
     (font-lock-reference-face ((t (:foreground "SlateBlue"))))
     (font-lock-string-face ((t (:foreground "#ff7a0a"))))
     (font-lock-type-face ((t (:foreground "SlateGrey"))))
     (font-lock-variable-name-face ((t (:foreground "darkseagreen"))))
     (font-lock-warning-face ((t (:bold t :foreground "yellow" :weight bold :underline "white"))))

     (isearch ((t (:background "#afdcfd" :foreground "black"))))
     (isearch-lazy-highlight-face ((t (:background "#fefab0" :foreground "black"))))
     ;; (isearch ((t (:background "#4e9a06" :foreground "#2e3436"))))
     ;; (isearch-lazy-highlight-face ((t (:background "#fefab0" :foreground "black"))))

     (italic ((t (:italic t))))
     (region ((t (:background "#282a37"))))
     (underline ((t (:underline t))))
	 )))

; zz

(add-to-list
 'color-themes
 '(color-theme-aaken-dark "Aaken Dark" "Tav Espian <tav@espians.com>"))
